## 데이터 불러오기

In [1]:
import seaborn as sns

In [4]:
iris = sns.load_dataset('iris')

print(iris)
print(type(iris))
print(iris.shape)
print(iris.info())

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]
<class 'pandas.core.frame.DataFrame'>
(150, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns

#### x,y 데이터 나누기

In [5]:
import pandas as pd

In [6]:
X_data = iris.iloc[:,:4]
y_data = iris.iloc[:,4]

print(X_data)
print(type(X_data))
print(X_data.shape)


print(y_data)
print(type(y_data))
print(y_data.shape)

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]
<class 'pandas.core.frame.DataFrame'>
(150, 4)
0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object
<cla

#### 클래스 라벨 인코딩

In [7]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(y_data)

le.classes_

y_data = le.transform(y_data)

print(y_data)
print(type(y_data))
print(y_data.shape)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
<class 'numpy.ndarray'>
(150,)


#### train test 셋 나누기

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train, x_test, y_train, y_test = train_test_split(
    X_data, y_data, test_size=0.33, random_state=42)

print(x_train)
print(type(x_train))
print(x_train.shape)
print(x_test)
print(type(x_test))
print(x_test.shape)
print(y_train)
print(type(y_train))
print(y_train.shape)
print(y_test)
print(type(y_test))
print(y_test.shape)

     sepal_length  sepal_width  petal_length  petal_width
96            5.7          2.9           4.2          1.3
105           7.6          3.0           6.6          2.1
66            5.6          3.0           4.5          1.5
0             5.1          3.5           1.4          0.2
122           7.7          2.8           6.7          2.0
..            ...          ...           ...          ...
71            6.1          2.8           4.0          1.3
106           4.9          2.5           4.5          1.7
14            5.8          4.0           1.2          0.2
92            5.8          2.6           4.0          1.2
102           7.1          3.0           5.9          2.1

[100 rows x 4 columns]
<class 'pandas.core.frame.DataFrame'>
(100, 4)
     sepal_length  sepal_width  petal_length  petal_width
73            6.1          2.8           4.7          1.2
18            5.7          3.8           1.7          0.3
118           7.7          2.6           6.9          2.3
7

## 로지스틱회귀 실행

LogisticRegression(C=200, random_state=0).fit(x_train,y_train)
- C= 양의 실수값  : 정규화의 정도를 정하는 속성

In [12]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(random_state=0).fit(x_train,y_train)

y_train_pred = clf.predict(x_train)
y_test_pred = clf.predict(x_test)

print(y_train_pred)
print(type(y_train_pred))
print(y_train_pred.shape)
print(y_test_pred)
print(type(y_test_pred))
print(y_test_pred.shape)

# 여기부터는 함수 뭔지 알려고 실행 해봄
print(clf.predict_proba(x_train))


print(clf.score(x_train, y_train))

[1 2 1 0 2 1 0 0 0 1 2 0 0 0 1 0 1 2 0 1 2 0 2 2 1 1 2 1 0 1 2 0 0 1 2 0 2
 0 0 2 1 2 2 2 2 1 0 0 2 2 0 0 0 1 2 0 2 2 0 1 1 2 1 2 0 2 1 2 1 1 1 0 1 1
 0 1 2 2 0 1 2 2 0 2 0 1 2 2 1 2 1 1 2 2 0 1 1 0 1 2]
<class 'numpy.ndarray'>
(100,)
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0 1 2 2 1 2]
<class 'numpy.ndarray'>
(50,)
[[2.08764943e-02 8.96650524e-01 8.24729820e-02]
 [2.74653520e-07 9.45894917e-03 9.90540776e-01]
 [1.08392752e-02 7.42758507e-01 2.46402218e-01]
 [9.73437879e-01 2.65619404e-02 1.80450197e-07]
 [1.66920263e-07 9.67310381e-03 9.90326729e-01]
 [2.07738552e-02 9.47808801e-01 3.14173436e-02]
 [9.67597812e-01 3.24019760e-02 2.12441366e-07]
 [9.79733004e-01 2.02668509e-02 1.44653079e-07]
 [9.46378153e-01 5.36198416e-02 2.00526686e-06]
 [6.01682531e-02 9.28627073e-01 1.12046739e-02]
 [9.54482401e-04 4.15265656e-01 5.83779861e-01]
 [9.35172258e-01 6.48259448e-02 1.79749711e-06]
 [9.34126989e-01 6.58721837e-02 8.27221495e-07]
 [9.3510

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


#### 모델 정확도 평가

In [13]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_train, y_train_pred, normalize=False)) # 정규화 않한 것
print(accuracy_score(y_test, y_test_pred)) # 정규화 디폴트 값



96
1.0


/////////////////////////////////////////////////////////////////////////////////////////

#### values 함수 알아보기
- 값만 넘파이 2차원 배열로 가져온다

In [14]:
x_train
print(x_train)
print(type(x_train))
print(x_train.shape)

x_train_value = X_data.iloc[:,:4].values
print(x_train_value)
print(type(x_train_value))
print(x_train_value.shape)

     sepal_length  sepal_width  petal_length  petal_width
96            5.7          2.9           4.2          1.3
105           7.6          3.0           6.6          2.1
66            5.6          3.0           4.5          1.5
0             5.1          3.5           1.4          0.2
122           7.7          2.8           6.7          2.0
..            ...          ...           ...          ...
71            6.1          2.8           4.0          1.3
106           4.9          2.5           4.5          1.7
14            5.8          4.0           1.2          0.2
92            5.8          2.6           4.0          1.2
102           7.1          3.0           5.9          2.1

[100 rows x 4 columns]
<class 'pandas.core.frame.DataFrame'>
(100, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8