In [ ]:
import seaborn as sns

In [ ]:
iris= sns.load_dataset('iris')
print(iris)

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]


In [ ]:
iris.info()
# iris.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


- 데이터 결측치 없다
- class가 object라 인코딩 해야 함

### x,y 데이터 나누기

In [ ]:
x = iris.drop("species",axis=1)
print(x.shape)


y = iris["species"]

(150, 4)


###원핫 인코딩

In [ ]:
from sklearn.preprocessing import LabelEncoder
import numpy as np

Enc =   LabelEncoder()
y = Enc.fit_transform(iris['species'].values)
print(np.unique(y)) # np.unique() 중복값 빼고 표현

[0 1 2]


### 인코딩 된것을 다시 범주화

In [ ]:
yo = Enc.inverse_transform(y)
print(yo)

['setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'v

### 학습,테스트 셋 나누기

train_test_split()
- random_state : 랜점 시드 설정
- stratify : 데이터 나눌 때 고루 뽑기 

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.3,random_state=1,stratify=y)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

     sepal_length  sepal_width  petal_length  petal_width
33            5.5          4.2           1.4          0.2
20            5.4          3.4           1.7          0.2
115           6.4          3.2           5.3          2.3
124           6.7          3.3           5.7          2.1
35            5.0          3.2           1.2          0.2
..            ...          ...           ...          ...
41            4.5          2.3           1.3          0.3
92            5.8          2.6           4.0          1.2
26            5.0          3.4           1.6          0.4
3             4.6          3.1           1.5          0.2
42            4.4          3.2           1.3          0.2

[105 rows x 4 columns]
     sepal_length  sepal_width  petal_length  petal_width
148           6.2          3.4           5.4          2.3
5             5.4          3.9           1.7          0.4
6             4.6          3.4           1.4          0.3
106           4.9          2.5           4.5    

### 모델 설계 및 학습

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3,p=2) # k개수, 거리특정 기준 2는 유클리드
knn.fit(x_train, y_train)



KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

예측값

In [ ]:
y_test_pred = knn.predict(x_test)
print(knn.predict(x_train))
print(knn.predict(x_test))

[0 0 2 2 0 2 2 0 2 1 1 1 0 1 1 2 0 1 1 0 2 2 1 1 1 2 1 2 2 2 1 0 2 2 2 2 1
 2 2 0 2 0 1 0 0 2 0 0 2 1 0 1 1 0 0 0 1 2 0 1 0 1 2 0 0 1 2 1 1 1 2 1 1 2
 2 1 0 0 2 2 2 1 0 1 2 2 0 0 2 0 2 1 1 1 0 2 1 0 0 1 0 1 0 0 0]
[2 0 0 1 1 1 2 1 2 0 0 2 0 1 0 1 2 1 1 2 2 0 1 2 1 1 1 2 0 2 0 0 1 1 2 2 0
 0 0 1 2 2 1 0 0]


y_test 와 예측값 비교로 모델 정확도 출력

In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_test_pred))

0.9777777777777777


### 데이터 표준화(옵션)

- 표준화 할 땐
fit() 으로 평균 표준편차 계산 해놓고  

- transform(X) 으로 표준화 할 때는 transform 만 따로 해야 표준화 수행 됨



In [ ]:
from sklearn.preprocessing import StandardScaler
st = StandardScaler()
st.fit(x_train) # 평균 표준편차 계산 
x_train_std = st.transform(x_train) # 표준화 할 때는 transform 만 따로
x_test_std = st.transform(x_test)
print(x_train)
print(x_train_std)
print(x_test_std)

     sepal_length  sepal_width  petal_length  petal_width
33            5.5          4.2           1.4          0.2
20            5.4          3.4           1.7          0.2
115           6.4          3.2           5.3          2.3
124           6.7          3.3           5.7          2.1
35            5.0          3.2           1.2          0.2
..            ...          ...           ...          ...
41            4.5          2.3           1.3          0.3
92            5.8          2.6           4.0          1.2
26            5.0          3.4           1.6          0.4
3             4.6          3.1           1.5          0.2
42            4.4          3.2           1.3          0.2

[105 rows x 4 columns]
[[-0.4301064   2.63118533 -1.33269725 -1.30728421]
 [-0.55053619  0.76918392 -1.16537974 -1.30728421]
 [ 0.65376173  0.30368356  0.84243039  1.44587881]
 [ 1.0150511   0.53643374  1.0655204   1.18367281]
 [-1.03225536  0.30368356 -1.44424226 -1.30728421]
 [ 1.0150511   0.07093339

#### 모델 적용

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn2 = KNeighborsClassifier(n_neighbors=5,p=2)
knn2.fit(x_train_std,y_train)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
y_train_pred2 = knn2.predict(x_train_std)
y_test_pred2 = knn2.predict(x_test_std)
print(y_train_pred2)
print(y_test_pred2)

[0 0 2 2 0 2 2 0 2 1 1 1 0 1 1 2 0 1 1 0 2 2 1 1 1 2 1 1 2 2 1 0 2 2 1 2 1
 2 2 0 2 0 2 0 0 2 0 0 2 1 0 1 1 0 0 0 1 2 0 1 0 1 2 0 0 1 2 1 1 1 2 1 1 2
 2 1 0 0 2 2 2 2 0 1 2 2 0 0 2 0 2 1 1 1 0 2 1 0 0 1 0 1 0 0 0]
[2 0 0 1 1 1 2 2 2 0 0 2 0 1 0 1 2 1 1 2 2 0 1 2 1 1 1 2 0 2 0 0 1 1 2 2 0
 0 0 1 2 2 2 0 0]


### 결과 분석

In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_test_pred2))

0.9333333333333333


- 표준화 없이 정확도 : 9.77
표준화 있이 : 9.33 으로 하락  
- 데이터에 따라 정확도 증감 다름